-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_log (
  id bigint NOT NULL DEFAULT nextval('audit_log_id_seq'::regclass),
  action text NOT NULL,
  user_id text,
  username text,
  ip text,
  user_agent text,
  meta jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.categories (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  workspace text DEFAULT 'principal'::text,
  name text NOT NULL,
  description text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clients (
  id text NOT NULL,
  workspace text DEFAULT 'principal'::text,
  name text NOT NULL,
  document text,
  tel text,
  email text,
  status text DEFAULT 'interessado'::text CHECK (status = ANY (ARRAY['interessado'::text, 'visitado'::text, 'agendado'::text, 'comprou'::text, 'naointeressado'::text, 'retornar'::text, 'outro'::text])),
  address text,
  city text,
  state text,
  zip_code text,
  lat double precision,
  lng double precision,
  maps_link text,
  obs text,
  indicado text,
  user_id text,
  document_front_path text,
  document_back_path text,
  residence_proof_path text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tel2 text,
  category text DEFAULT 'geral'::text,
  CONSTRAINT clients_pkey PRIMARY KEY (id)
);
CREATE TABLE public.commissions (
  id text NOT NULL,
  workspace text DEFAULT 'principal'::text,
  referral_id text,
  referral_name text,
  order_id text,
  client_id text,
  client_name text,
  amount numeric NOT NULL,
  commission_type text DEFAULT 'fixed'::text,
  status text DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'paga'::text, 'cancelada'::text])),
  receipt_photo_ids jsonb DEFAULT '[]'::jsonb,
  paid_at timestamp with time zone,
  order_date date,
  order_total numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT commissions_pkey PRIMARY KEY (id),
  CONSTRAINT commissions_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id),
  CONSTRAINT commissions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT commissions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.companies (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  name text NOT NULL,
  trade_name text,
  document text,
  address text,
  city text,
  state text,
  zip_code text,
  phone text,
  email text,
  logo_url text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.environments (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  workspace text DEFAULT 'principal'::text,
  client_id text,
  name text NOT NULL,
  area numeric,
  area_unit text DEFAULT 'ha'::text,
  obs text,
  lat double precision,
  lng double precision,
  drawing jsonb,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT environments_pkey PRIMARY KEY (id),
  CONSTRAINT environments_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.km_logs (
  id text NOT NULL,
  user_id text,
  data date NOT NULL,
  veiculo text,
  km_ini double precision NOT NULL,
  km_fim double precision NOT NULL,
  percorrido double precision NOT NULL,
  combustivel double precision DEFAULT 0,
  consumo double precision,
  litros double precision,
  custo_por_km double precision,
  obs text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT km_logs_pkey PRIMARY KEY (id),
  CONSTRAINT km_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.order_items (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  order_id text,
  product_id text,
  product_name text,
  quantity numeric DEFAULT 1,
  unit_price numeric DEFAULT 0,
  total numeric DEFAULT 0,
  rep_commission_pct numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.orders (
  id text NOT NULL,
  workspace text DEFAULT 'principal'::text,
  order_number bigint,
  client_id text,
  referral_id text,
  environment_id text,
  user_id text,
  date date DEFAULT CURRENT_DATE,
  status text DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'aprovado'::text, 'pago'::text, 'cancelado'::text, 'faturado'::text])),
  total numeric DEFAULT 0,
  discount numeric DEFAULT 0,
  commission_type text DEFAULT 'percent'::text,
  commission_pct numeric DEFAULT 0,
  commission_value numeric DEFAULT 0,
  obs text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT orders_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id),
  CONSTRAINT orders_environment_id_fkey FOREIGN KEY (environment_id) REFERENCES public.environments(id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.photos (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  workspace text DEFAULT 'principal'::text,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_url text NOT NULL,
  file_size bigint,
  mime_type text,
  uploaded_by text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT photos_pkey PRIMARY KEY (id),
  CONSTRAINT photos_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.pre_registrations (
  id text NOT NULL,
  workspace text DEFAULT 'principal'::text,
  name text NOT NULL,
  tel text,
  email text,
  interest text,
  source text DEFAULT 'site'::text,
  status text DEFAULT 'novo'::text CHECK (status = ANY (ARRAY['novo'::text, 'contatado'::text, 'qualificado'::text, 'convertido'::text, 'perdido'::text])),
  obs text,
  converted_client_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pre_registrations_pkey PRIMARY KEY (id),
  CONSTRAINT pre_registrations_converted_client_id_fkey FOREIGN KEY (converted_client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.products (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  workspace text DEFAULT 'principal'::text,
  category_id text,
  name text NOT NULL,
  description text,
  sku text,
  finame_code text DEFAULT ''::text,
  ncm_code text DEFAULT ''::text,
  unit_price numeric DEFAULT 0,
  cost_price numeric DEFAULT 0,
  stock_qty numeric DEFAULT 0,
  unit text DEFAULT 'UN'::text,
  rep_commission_pct numeric DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  model text,
  color text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.rate_limits (
  id bigint NOT NULL DEFAULT nextval('rate_limits_id_seq'::regclass),
  key text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.referrals (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  workspace text DEFAULT 'principal'::text,
  name text NOT NULL,
  document text,
  tel text,
  email text,
  commission_type text DEFAULT 'fixed'::text CHECK (commission_type = ANY (ARRAY['fixed'::text, 'percent'::text])),
  commission_pct numeric DEFAULT 0,
  commission numeric DEFAULT 0,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  bank_name text,
  bank_agency text,
  bank_account text,
  bank_pix text,
  CONSTRAINT referrals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rep_commissions (
  id text NOT NULL,
  workspace text DEFAULT 'principal'::text,
  order_id text,
  order_item_id text,
  order_date date,
  client_id text,
  client_name text,
  product_id text,
  product_name text,
  qty numeric DEFAULT 1,
  unit_price numeric DEFAULT 0,
  rep_commission_pct numeric DEFAULT 0,
  amount numeric NOT NULL,
  order_total numeric,
  status text DEFAULT 'pendente'::text CHECK (status = ANY (ARRAY['pendente'::text, 'paga'::text, 'cancelada'::text])),
  receipt_photo_ids jsonb DEFAULT '[]'::jsonb,
  paid_at timestamp with time zone,
  reprocessed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rep_commissions_pkey PRIMARY KEY (id),
  CONSTRAINT rep_commissions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT rep_commissions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT rep_commissions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.settings (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  workspace text DEFAULT 'principal'::text UNIQUE,
  company_id text,
  config jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  dev_pin_hash text,
  dev_mode_expires timestamp with time zone,
  CONSTRAINT settings_pkey PRIMARY KEY (id),
  CONSTRAINT settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.users (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  username text NOT NULL UNIQUE,
  email text UNIQUE,
  pass_hash text NOT NULL,
  hash_algo text DEFAULT 'bcrypt'::text CHECK (hash_algo = ANY (ARRAY['sha256'::text, 'bcrypt'::text])),
  role text DEFAULT 'user'::text CHECK (role = ANY (ARRAY['admin'::text, 'user'::text, 'manager'::text])),
  active boolean DEFAULT true,
  failed_logins integer DEFAULT 0,
  locked_until timestamp with time zone,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  workspace text DEFAULT 'principal'::text,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.visits (
  id text NOT NULL,
  workspace text DEFAULT 'principal'::text,
  client_id text,
  user_id text,
  activity_type text DEFAULT 'Visita'::text CHECK (activity_type = ANY (ARRAY['Visita'::text, 'Ligação'::text, 'WhatsApp'::text, 'Email'::text, 'Reunião'::text])),
  scheduled_date timestamp with time zone,
  visit_date timestamp with time zone,
  status text DEFAULT 'agendado'::text CHECK (status = ANY (ARRAY['agendado'::text, 'realizado'::text, 'cancelado'::text, 'nao_compareceu'::text])),
  obs text,
  lat double precision DEFAULT 0,
  lng double precision DEFAULT 0,
  photos jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT visits_pkey PRIMARY KEY (id),
  CONSTRAINT visits_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT visits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);